Vagrant.configure("2") do |config|
  # Ubuntu Jammy
  config.vm.define "ubuntu-jammy" do |srv|
    srv.vm.box = "ubuntu/jammy64"
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "ubuntu-jammy-vm"
      vb.customize ['modifyvm', :id, '--audio', 'none']
    end

    # Синхронизация папок
    srv.vm.synced_folder "./", "/vagrant"

    # Подключение диска
    srv.vm.disk :disk, size: "1GB", name: "disk1"

    # Проброс порта для HTTP (будет доступен по localhost:8080)
    srv.vm.network(:forwarded_port,
                    guest: 80,
                    host: 8080,
                    host_ip: "127.0.0.1")

    # Приватная сеть в той же подсети, что и virbr0 на хосте (192.168.122.0/24)
    srv.vm.network(:private_network,
                   ip: "192.168.56.11",
                   libvirt__network_name: "default",  # Это для Libvirt, но для VirtualBox просто укажите IP
                   auto_config: true)

    # Provisioning - установка Apache
    srv.vm.provision "shell", inline: <<-SHELL
      # Обновление пакетов
      sudo apt-get update
      
      # Установка Apache
      sudo apt-get install -y apache2
      
      # Отключаем стандартную папку /var/www/html
      sudo a2dissite 000-default.conf
      
      # Создаем конфигурацию для нашего сайта
      echo "<VirtualHost *:80>
          DocumentRoot /vagrant
          <Directory /vagrant>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>
      </VirtualHost>" | sudo tee /etc/apache2/sites-available/vagrant.conf
      
      # Включаем наш сайт
      sudo a2ensite vagrant.conf
      
      # Включение mod_rewrite
      sudo a2enmod rewrite
      
      # Перезапуск Apache
      sudo systemctl restart apache2
    SHELL
  end
end
