Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  config.vm.boot_timeout = 600
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "web2" do |web|
    web.vm.hostname = "web2.example.com"
    # ИСПРАВЛЕНО: убрать type: "dhcp"
    web.vm.network "private_network", ip: "192.168.56.11"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
      vb.name = "ansible-demo-web2"
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      # включаем promisc на host-only адаптере
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end
end