Vagrant.configure("2") do |config|
  # Базовая VM с Debian 12
  config.vm.define "debian12" do |srv|
    srv.vm.box = "debian/bullseye64"
    srv.vm.hostname = "debian11-vm"
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end