Vagrant.configure("2") do |config|
  # Используем проверенный box
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  
  # Увеличиваем таймаут
  config.vm.boot_timeout = 600
  
  # Отключаем синхронизацию папок для скорости
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Database Server
  config.vm.define "db1" do |db|
    db.vm.hostname = "db1.example.com"
    # УБЕРИТЕ type: "dhcp" - используйте либо статический IP, либо DHCP
    db.vm.network "private_network", ip: "192.168.56.20"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "ansible-demo-db1"
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  end
end