Vagrant.configure("2") do |config|
  # Ubuntu Jammy
  config.vm.define "ubuntu-jammy" do |srv|
    srv.vm.box = "ubuntu/jammy64"
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "ubuntu-jammy-vm"
      vb.customize ['modifyvm', :id, '--audio', 'none']
    end

    # Синхронизация папок
    srv.vm.synced_folder "./", "/vagrant"

    # Подключение диска
    srv.vm.disk :disk, size: "1GB", name: "disk1"

    # Приватная сеть с IP, который не конфликтует с NAT хоста
    srv.vm.network(:private_network, ip: "192.168.56.11")

    # Проброс порта для SSH
    srv.vm.network(:forwarded_port,
                    guest: 22,
                    host: 3022)

    # Внутренняя сеть с уникальным именем
    srv.vm.network(:private_network,
                   ip: "192.168.56.12",
                   intnet: "otus-net")

    # Публичная сеть с указанием интерфейса
    srv.vm.network "public_network", bridge: "enp0s3"
  end
end