Vagrant.configure("2") do |config|
  # Debian 11
  config.vm.define "debian11" do |srv|
    srv.vm.box = "generic/debian11"
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # Ubuntu Jammy
  config.vm.define "ubuntu-jammy" do |srv|
    srv.vm.box = "ubuntu/jammy64"
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "ubuntu-jammy-vm"
      vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
      vb.customize ['modifyvm', :id, '--audio', 'none']
    end
  end
end

